version: "3.8"

services:
  frontend:
    image: projectwork2024-frontend
    build:
      context: ./frontend
    ports:
      - "3000"
    networks:
      - app-network

  webserver:
    image: projectwork2024-webserver
    build:
      context: ./webserver
    ports:
      - "5000:5000"
    networks:
      - app-network    

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
