version: "3.8"

services:
  frontend:
    image: projectwork2024-frontend
    build:
      context: ./frontend
    networks:
      - app-network
    deploy:
      replicas: 3

  webserver:
    image: projectwork2024-webserver
    build:
      context: ./webserver
    networks:
      - app-network
    deploy:
      replicas: 3    

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - webserver
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
